### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Cathella** [tacodtripe/New-York-Times-Clone-Page#4]

**Comment by ricardo123321** [comment]
add a min-width and max to the images to make them resizable

**Comment by ricardo123321** [comment]
add a grid system

**Comment by ricardo123321** [comment]
use em or percentages in your objects

**Comment by hemantso** [comment]
alignment of navbar use  flex 
sizing of font make it font-weight to 700 
use grid for multiple images

**Comment by LoboArkano** [comment]
In the navigation bar, use <a> in the New York Times logo with the link to the home page (www.nytimes.com).

**Comment by Cathella** [comment]
Thanks team.
